import { execFile } from "node:child_process";
import { access, mkdir } from "node:fs/promises";
import path from "node:path";

export type SyncMode = "merge" | "rebase";

export type SyncInput = {
  upstream: string;
  fork: string;
  upstreamBranch: string;
  forkBranch: string;
  branch: string;
  mode: SyncMode;
  testCommands: string[];
  execute: boolean;
  push: boolean;
  createPr: boolean;
  workdir?: string;
};

export type SyncStep = {
  command: string;
  status: "planned" | "passed" | "failed";
  output?: string;
};

export type SyncResult = {
  markdown: string;
  steps: SyncStep[];
};

type ExecImpl = (
  command: string,
  args: string[],
  options: { cwd?: string; timeout: number; maxBuffer: number },
) => Promise<{ stdout: string; stderr: string }>;

export async function runSyncWorkflow(
  input: SyncInput,
  execImpl: ExecImpl = execFilePromise,
): Promise<SyncResult> {
  const root = path.resolve(input.workdir || ".cache/sync");
  const repoDir = await nextRepoDir(root, input);
  const steps = buildSyncSteps(input, repoDir);

  if (!input.execute) {
    return {
      steps,
      markdown: formatSyncMarkdown(input, steps),
    };
  }

  await mkdir(root, { recursive: true });
  const executed: SyncStep[] = [];
  for (const step of steps) {
    try {
      const [command, ...args] = splitCommand(step.command);
      const output = await execImpl(command, args, {
        cwd: step.command.startsWith("git clone") ? root : repoDir,
        timeout: 120000,
        maxBuffer: 1024 * 1024 * 12,
      });
      executed.push({
        ...step,
        status: "passed",
        output: compactOutput(output.stdout, output.stderr),
      });
    } catch (caught) {
      executed.push({
        ...step,
        status: "failed",
        output: caught instanceof Error ? caught.message : String(caught),
      });
      return {
        steps: executed,
        markdown: formatSyncMarkdown(input, executed),
      };
    }
  }

  return {
    steps: executed,
    markdown: formatSyncMarkdown(input, executed),
  };
}

export function buildSyncSteps(input: SyncInput, repoDir = repoDirName(input.fork)): SyncStep[] {
  const upstreamUrl = githubCloneUrl(input.upstream);
  const forkUrl = githubCloneUrl(input.fork);
  const backup = `backup/fork-drift-before-sync-${input.forkBranch.replaceAll("/", "-")}`;
  const steps = [
    `git clone ${forkUrl} ${repoDir}`,
    `git remote add upstream ${upstreamUrl}`,
    `git fetch --prune origin ${input.forkBranch}`,
    `git fetch --prune upstream ${input.upstreamBranch}`,
    `git switch -C ${input.branch} origin/${input.forkBranch}`,
    `git branch ${backup} origin/${input.forkBranch}`,
    input.mode === "merge"
      ? `git merge --no-ff upstream/${input.upstreamBranch}`
      : `git rebase upstream/${input.upstreamBranch}`,
    ...input.testCommands,
    ...(input.push ? [`git push --force-with-lease origin HEAD:${input.branch}`] : []),
    ...(input.createPr
      ? [
          `gh pr create --repo ${input.fork} --head ${input.branch} --base ${input.forkBranch} --title "sync upstream ${input.upstreamBranch} into ${input.forkBranch}" --body "Generated by Fork Drift Sentinel."`,
        ]
      : []),
  ];

  return steps.map((command) => ({ command, status: "planned" }));
}

function formatSyncMarkdown(input: SyncInput, steps: SyncStep[]): string {
  return [
    "## Downstream Sync Workflow",
    "",
    `Mode: ${input.mode}`,
    `Execute: ${String(input.execute)}`,
    `Push: ${String(input.push)}`,
    `Create PR: ${String(input.createPr)}`,
    "",
    `Upstream: \`${input.upstream}\` branch \`${input.upstreamBranch}\``,
    `Fork: \`${input.fork}\` branch \`${input.forkBranch}\``,
    `Sync branch: \`${input.branch}\``,
    "",
    "### Steps",
    ...steps.map((step, index) =>
      [
        `${index + 1}. ${statusLabel(step.status)} \`${step.command}\``,
        step.output ? `   - ${step.output}` : "",
      ].filter(Boolean).join("\n"),
    ),
    "",
    "_Push and PR creation only run when their explicit flags are present._",
  ].join("\n");
}

function statusLabel(status: SyncStep["status"]): string {
  if (status === "passed") {
    return "passed";
  }
  if (status === "failed") {
    return "failed";
  }
  return "planned";
}

function githubCloneUrl(repo: string): string {
  return `https://github.com/${repo.replace(/^https:\/\/github\.com\//, "").replace(/\.git$/, "")}.git`;
}

function repoDirName(repo: string): string {
  return repo.toLowerCase().replace(/[^a-z0-9_.-]+/g, "-");
}

async function nextRepoDir(root: string, input: SyncInput): Promise<string> {
  const base = path.join(root, `${repoDirName(input.fork)}-${repoDirName(input.branch)}`);
  try {
    await access(base);
  } catch {
    return base;
  }
  return `${base}-${Date.now()}`;
}

function splitCommand(command: string): string[] {
  return command.match(/(?:[^\s"]+|"[^"]*")+/g)?.map((part) =>
    part.replace(/^"|"$/g, ""),
  ) ?? [];
}

function compactOutput(stdout: string, stderr: string): string {
  return `${stdout}\n${stderr}`
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(-6)
    .join(" | ");
}

function execFilePromise(
  command: string,
  args: string[],
  options: { cwd?: string; timeout: number; maxBuffer: number },
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(command, args, options, (error, stdout, stderr) => {
      if (error) {
        reject(
          new Error(
            `${command} ${args.join(" ")} failed: ${stderr || stdout || error.message}`,
          ),
        );
        return;
      }
      resolve({ stdout: String(stdout), stderr: String(stderr) });
    });
  });
}
